version: '3.8'
services:
 db:
    image: statestitle/postgres13:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

 backend:
    depends_on:
      - db
    build: ./backend
    image: backendapp
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
 frontend:
      build: ./frontend
      image: frontend
      ports:
        - "8081:8081"
